--liquibase formatted sql

--changeset Patrick Heidotting:1

ALTER TABLE `POLIS` MODIFY `SOORT` VARCHAR(2);

--changeset Patrick Heidotting:2

ALTER TABLE `POLIS_AUD` MODIFY `SOORT` VARCHAR(2);

ALTER TABLE `OPMERKING` ADD COLUMN TIJD datetime NOT NULL;
ALTER TABLE `OPMERKING_AUD` ADD COLUMN TIJD datetime NOT NULL;

--changeset Patrick Heidotting:3

ALTER TABLE `POLIS` ADD COLUMN POLISNUMMER VARCHAR(25) NOT NULL AFTER `INGANGSDATUM`;
ALTER TABLE `POLIS_AUD` ADD COLUMN POLISNUMMER VARCHAR(25) AFTER `INGANGSDATUM`;

--changeset Patrick Heidotting:4

ALTER TABLE `VERZEKERINGSMAATSCHAPPIJ` ADD COLUMN TONEN tinyint(1) NOT NULL DEFAULT '1' AFTER `NAAM`;
ALTER TABLE `VERZEKERINGSMAATSCHAPPIJ_AUD` ADD COLUMN TONEN tinyint(1) AFTER `NAAM`;

INSERT INTO `VERZEKERINGSMAATSCHAPPIJ` (`NAAM`) VALUES ('Achmea');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ` (`NAAM`) VALUES ('Aegon');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ` (`NAAM`) VALUES ('Agis');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ` (`NAAM`) VALUES ('Allianz Nederland');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ` (`NAAM`) VALUES ('AllSecur');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ` (`NAAM`) VALUES ('Amersfoortse (de)');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ` (`NAAM`) VALUES ('ASR Verzekeringen');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ` (`NAAM`) VALUES ('Avero Achmea');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ` (`NAAM`) VALUES ('Crisper');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ` (`NAAM`) VALUES ('Delta Lloyd');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ` (`NAAM`) VALUES ('Ditzo');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ` (`NAAM`) VALUES ('Generali');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ` (`NAAM`) VALUES ('Goudse (de)');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ` (`NAAM`) VALUES ('Kilometerverzekering (de)');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ` (`NAAM`) VALUES ('Klaverblad');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ` (`NAAM`) VALUES ('Kruidvat');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ` (`NAAM`) VALUES ('London Verzekeringen');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ` (`NAAM`) VALUES ('Nationale Nederlanden');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ` (`NAAM`) VALUES ('OHRA');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ` (`NAAM`) VALUES ('Polis Direct');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ` (`NAAM`) VALUES ('SNS Bank');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ` (`NAAM`) VALUES ('Turien & Co');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ` (`NAAM`) VALUES ('Unive');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ` (`NAAM`) VALUES ('Verzekeruzelf.nl');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ` (`NAAM`) VALUES ('Zelf.nl');

--changeset Patrick Heidotting:5

ALTER TABLE `POLIS_AUD` ADD COLUMN `KENTEKEN` varchar(10) DEFAULT NULL AFTER `OMSCHRIJVING`;
ALTER TABLE `POLIS_AUD` ADD COLUMN `SOORTAUTOVERZEKERING` varchar(10) DEFAULT NULL AFTER `KENTEKEN`;
ALTER TABLE `POLIS` ADD COLUMN OLDTIMER tinyint(1) AFTER `SOORTAUTOVERZEKERING`;
ALTER TABLE `POLIS_AUD` ADD COLUMN OLDTIMER tinyint(1) AFTER `SOORTAUTOVERZEKERING`;

--changeset Patrick Heidotting:6

INSERT INTO `GEBRUIKER` (`SOORT`, `ID`, `EMAILADRES`, `SALT`, `WACHTWOORD`, `ACHTERNAAM`, `VOORNAAM`) VALUES ('B', 1, 'patrick@lakedigital.nl', '374b2ed3c4f8c0ea4832dc036ef98134c141f3abfad3ad969774a780e5a756ced90f6b4249b3bf93a89b52820afa7a15dfe86bb76a99215ebaba4d80bd7dae33', '65c36a56c8a45e686424fa4c8342e546093b61d1acb4479a4a4cc763ad48f2b1ddcdf78b4f1e591027ecc13c346f93c64655f1c946da5487312605791d0fa5a1', 'Heidotting', 'Patrick');
INSERT INTO `GEBRUIKER_AUD` (`SOORT`, `ID`, `REV`, `REVTYPE`, `ACHTERNAAM`, `VOORNAAM`) VALUES ('B', 1, 1, 0, 'Heidotting', 'Patrick');
INSERT INTO `REVINFO` (`timestamp`, `userid`) VALUES (0, NULL);
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ_AUD` (`ID`, `REV`, `REVTYPE`, `NAAM`, `TONEN`) VALUES ('1', '1', '0', 'Achmea', '1');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ_AUD` (`ID`, `REV`, `REVTYPE`, `NAAM`, `TONEN`) VALUES ('2', '1', '0', 'Aegon', '1');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ_AUD` (`ID`, `REV`, `REVTYPE`, `NAAM`, `TONEN`) VALUES ('3', '1', '0', 'Agis', '1');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ_AUD` (`ID`, `REV`, `REVTYPE`, `NAAM`, `TONEN`) VALUES ('4', '1', '0', 'Allianz Nederland', '1');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ_AUD` (`ID`, `REV`, `REVTYPE`, `NAAM`, `TONEN`) VALUES ('5', '1', '0', 'AllSecur', '1');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ_AUD` (`ID`, `REV`, `REVTYPE`, `NAAM`, `TONEN`) VALUES ('6', '1', '0', 'Amersfoortse (de)', '1');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ_AUD` (`ID`, `REV`, `REVTYPE`, `NAAM`, `TONEN`) VALUES ('7', '1', '0', 'ASR Verzekeringen', '1');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ_AUD` (`ID`, `REV`, `REVTYPE`, `NAAM`, `TONEN`) VALUES ('8', '1', '0', 'Avero Achmea', '1');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ_AUD` (`ID`, `REV`, `REVTYPE`, `NAAM`, `TONEN`) VALUES ('9', '1', '0', 'Crisper', '1');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ_AUD` (`ID`, `REV`, `REVTYPE`, `NAAM`, `TONEN`) VALUES ('10', '1', '0', 'Delta Lloyd', '1');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ_AUD` (`ID`, `REV`, `REVTYPE`, `NAAM`, `TONEN`) VALUES ('11', '1', '0', 'Ditzo', '1');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ_AUD` (`ID`, `REV`, `REVTYPE`, `NAAM`, `TONEN`) VALUES ('12', '1', '0', 'Generali', '1');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ_AUD` (`ID`, `REV`, `REVTYPE`, `NAAM`, `TONEN`) VALUES ('13', '1', '0', 'Goudse (de)', '1');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ_AUD` (`ID`, `REV`, `REVTYPE`, `NAAM`, `TONEN`) VALUES ('14', '1', '0', 'Kilometerverzekering (de)', '1');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ_AUD` (`ID`, `REV`, `REVTYPE`, `NAAM`, `TONEN`) VALUES ('15', '1', '0', 'Klaverblad', '1');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ_AUD` (`ID`, `REV`, `REVTYPE`, `NAAM`, `TONEN`) VALUES ('16', '1', '0', 'Kruidvat', '1');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ_AUD` (`ID`, `REV`, `REVTYPE`, `NAAM`, `TONEN`) VALUES ('17', '1', '0', 'London Verzekeringen', '1');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ_AUD` (`ID`, `REV`, `REVTYPE`, `NAAM`, `TONEN`) VALUES ('18', '1', '0', 'Nationale Nederlanden', '1');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ_AUD` (`ID`, `REV`, `REVTYPE`, `NAAM`, `TONEN`) VALUES ('19', '1', '0', 'OHRA', '1');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ_AUD` (`ID`, `REV`, `REVTYPE`, `NAAM`, `TONEN`) VALUES ('20', '1', '0', 'Polis Direct', '1');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ_AUD` (`ID`, `REV`, `REVTYPE`, `NAAM`, `TONEN`) VALUES ('21', '1', '0', 'SNS Bank', '1');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ_AUD` (`ID`, `REV`, `REVTYPE`, `NAAM`, `TONEN`) VALUES ('22', '1', '0', 'Turien & Co', '1');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ_AUD` (`ID`, `REV`, `REVTYPE`, `NAAM`, `TONEN`) VALUES ('23', '1', '0', 'Unive', '1');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ_AUD` (`ID`, `REV`, `REVTYPE`, `NAAM`, `TONEN`) VALUES ('24', '1', '0', 'Verzekeruzelf.nl', '1');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ_AUD` (`ID`, `REV`, `REVTYPE`, `NAAM`, `TONEN`) VALUES ('25', '1', '0', 'Zelf.nl', '1');

--changeset Patrick Heidotting:7

ALTER TABLE `POLIS` ADD COLUMN `PREMIE` double DEFAULT NULL AFTER `POLISNUMMER`;
ALTER TABLE `POLIS_AUD` ADD COLUMN `PREMIE` double DEFAULT NULL AFTER `POLISNUMMER`;
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ` (`NAAM`) VALUES ('Unigarant');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ` (`NAAM`) VALUES ('Voogd en Voogd');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ` (`NAAM`) VALUES ('VKG');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ` (`NAAM`) VALUES ('DAS');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ` (`NAAM`) VALUES ('Europeesche');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ` (`NAAM`) VALUES ('Erasmus');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ` (`NAAM`) VALUES ('Monuta');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ` (`NAAM`) VALUES ('Onderlinge');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ` (`NAAM`) VALUES ('Reaal');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ_AUD` (`ID`, `REV`, `REVTYPE`, `NAAM`, `TONEN`) VALUES ('26', '1', '0', 'Unigarant', '1');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ_AUD` (`ID`, `REV`, `REVTYPE`, `NAAM`, `TONEN`) VALUES ('27', '1', '0', 'Voogd en Voogd', '1');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ_AUD` (`ID`, `REV`, `REVTYPE`, `NAAM`, `TONEN`) VALUES ('28', '1', '0', 'VKG', '1');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ_AUD` (`ID`, `REV`, `REVTYPE`, `NAAM`, `TONEN`) VALUES ('29', '1', '0', 'DAS', '1');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ_AUD` (`ID`, `REV`, `REVTYPE`, `NAAM`, `TONEN`) VALUES ('30', '1', '0', 'Europeesche', '1');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ_AUD` (`ID`, `REV`, `REVTYPE`, `NAAM`, `TONEN`) VALUES ('31', '1', '0', 'Europeesche', '1');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ_AUD` (`ID`, `REV`, `REVTYPE`, `NAAM`, `TONEN`) VALUES ('32', '1', '0', 'Monuta', '1');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ_AUD` (`ID`, `REV`, `REVTYPE`, `NAAM`, `TONEN`) VALUES ('33', '1', '0', 'Onderlinge', '1');
INSERT INTO `VERZEKERINGSMAATSCHAPPIJ_AUD` (`ID`, `REV`, `REVTYPE`, `NAAM`, `TONEN`) VALUES ('34', '1', '0', 'Reaal', '1');

--changeset Patrick Heidotting:8

ALTER TABLE `POLIS` DROP COLUMN `OMSCHRIJVING`;
ALTER TABLE `POLIS_AUD` DROP COLUMN `OMSCHRIJVING`;

--changeset Patrick Heidotting:9

ALTER TABLE `POLIS` ADD COLUMN`BEDRIJF` bigint(20) DEFAULT NULL AFTER `OLDTIMER`;
ALTER TABLE `POLIS_AUD` ADD COLUMN`BEDRIJF` bigint(20) DEFAULT NULL AFTER `OLDTIMER`;
ALTER TABLE `POLIS` ADD KEY `FK48C681741B2D649` (`BEDRIJF`);
CREATE TABLE `BEDRIJF` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `HUISNUMMER` bigint(20) DEFAULT NULL,
  `PLAATS` varchar(255) DEFAULT NULL,
  `POSTCODE` varchar(6) DEFAULT NULL,
  `STRAAT` varchar(255) DEFAULT NULL,
  `TOEVOEGING` varchar(255) DEFAULT NULL,
  `KVK` varchar(8) DEFAULT NULL,
  `NAAM` varchar(255) DEFAULT NULL,
  `RELATIE` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK1CFE4994DF4C9431` (`RELATIE`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=3 ;

CREATE TABLE `BEDRIJF_AUD` (
  `ID` bigint(20) NOT NULL,
  `REV` int(11) NOT NULL,
  `REVTYPE` tinyint(4) DEFAULT NULL,
  `HUISNUMMER` bigint(20) DEFAULT NULL,
  `PLAATS` varchar(255) DEFAULT NULL,
  `POSTCODE` varchar(6) DEFAULT NULL,
  `STRAAT` varchar(255) DEFAULT NULL,
  `TOEVOEGING` varchar(255) DEFAULT NULL,
  `KVK` varchar(8) DEFAULT NULL,
  `NAAM` varchar(255) DEFAULT NULL,
  `RELATIE` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`,`REV`),
  KEY `FK7B038D65D04A6114` (`REV`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--changeset Patrick Heidotting:10

ALTER TABLE `POLIS` ADD COLUMN `BETAALFREQUENTIE` varchar(1) DEFAULT NULL AFTER `ID`;
ALTER TABLE `POLIS_AUD` ADD COLUMN `BETAALFREQUENTIE` varchar(1) DEFAULT NULL AFTER `ID`;
ALTER TABLE `POLIS` ADD COLUMN `PROLONGATIEDATUM` date DEFAULT NULL AFTER `PREMIE`;
ALTER TABLE `POLIS_AUD` ADD COLUMN `PROLONGATIEDATUM` date DEFAULT NULL AFTER `PREMIE`;
ALTER TABLE `POLIS` ADD COLUMN `WIJZIGINGSDATUM` date DEFAULT NULL AFTER `PREMIE`;
ALTER TABLE `POLIS_AUD` ADD COLUMN `WIJZIGINGSDATUM` date DEFAULT NULL AFTER `PREMIE`;

--changeset Patrick Heidotting:11

INSERT INTO `KANTOOR` (`ID`, `HUISNUMMER`, `PLAATS`, `POSTCODE`, `STRAAT`, `TOEVOEGING`, `BTW_NUMMER`, `DATUMOPRICHTING`, `EMAILADRES`, `HUISNUMMER_FACTUUR`, `PLAATS_FACTUUR`, `POSTCODE_FACTUUR`, `STRAAT_FACTUUR`, `TOEVOEGING_FACTUUR`, `KVK`, `NAAM`, `RECHTSVORM`, `SOORTKANTOOR`) VALUES (NULL, '8', 'Emmen', '7827NH', 'Sierduif', NULL, '', '2014-05-09', 'info@dejongefinancieelconsult.nl', NULL, NULL, NULL, NULL, NULL, '04077584', 'De Jonge Financieel Consult', 'VOF', 'VZ');

--changeset Patrick Heidotting:12

DROP TABLE `BEDRIJF_AUD`;
DROP TABLE `BIJLAGE_AUD`;
DROP TABLE `GEBRUIKER_AUD`;
DROP TABLE `KANTOOR_AUD`;
DROP TABLE `ONDERLINGERELATIES_AUD`;
DROP TABLE `OPMERKING_AUD`;
DROP TABLE `POLIS_AUD`;
DROP TABLE `REKENINGNUMMER_AUD`;
DROP TABLE `SESSIE_AUD`;
DROP TABLE `TELEFOONNUMMER_AUD`;
DROP TABLE `VERZEKERINGSMAATSCHAPPIJ_AUD`;

--changeset Patrick Heidotting:13

ALTER TABLE `POLIS` DROP `KENTEKEN`;
ALTER TABLE `POLIS` DROP `SOORTAUTOVERZEKERING`;
ALTER TABLE `POLIS` DROP `OLDTIMER`;
